Google get chat
d4data-official/d4data-archive-lib pull request #32
Opened 2021-04-05 12:46 UTC by NathanBonnot

2021-04-05 14:04 UTC, ThalusA submitted a review, later dismissed

2021-04-05 14:13 UTC, jess-sys requested changes
Not using the correct way to extract messages (to avoid RAM overload)

Please see Facebook's getChats implementation. 
You also need to implement the getChatMessages function.

2021-05-08 12:05 UTC, jess-sys submitted a review, later dismissed
OK (Yeah I read the code)

2021-05-08 12:44 UTC, ThalusA approved these changes

2021-05-08 16:10 UTC, jess-sys approved these changes

2021-05-08 16:11 UTC, merged