Add getApi Discord
d4data-official/d4data-archive-lib pull request #33
Opened 2021-04-05 13:36 UTC by Szaborg

2021-04-05 15:04 UTC, ThalusA requested changes

2021-04-05 15:04 UTC, ThalusA commented on src/classes/Standardizer/plugins/Discord/getters/getAPI.ts
> +    parsedFiles: ['user.json'],
```suggestion
    parsedFiles: ['account/user.json'],
```
Invalid file path

2021-04-05 15:06 UTC, ThalusA submitted a review, later dismissed

2021-05-08 16:13 UTC, jess-sys approved these changes

2021-05-08 16:13 UTC, ThalusA approved these changes

2021-05-08 16:13 UTC, merged