Add parseAsVCARD
d4data-official/d4data-archive-lib pull request #41
Opened 2021-04-07 12:11 UTC by Szaborg

2021-04-07 12:28 UTC, jess-sys requested changes

2021-04-07 12:28 UTC, jess-sys commented on src/modules/Parsing/parseAsVCARD.ts
> +  const vCard = require('vcf')
Use import at the top of the file. If you don't know how to do it please **learn**.

2021-05-08 12:19 UTC, ThalusA submitted a review, later dismissed

2021-05-08 14:07 UTC, jess-sys submitted a review, later dismissed

2021-05-08 14:09 UTC, ThalusA submitted a review, later dismissed

2021-05-08 14:15 UTC, jess-sys commented
Fixed yarn.lock. No need for a manual review. Forcing.

2021-05-08 14:15 UTC, merged

2021-05-08 15:53 UTC, jess-sys commented
Ridiculous.