Add Events getter to Standardizer
d4data-official/d4data-archive-lib pull request #82
Opened 2021-05-24 17:26 UTC by super-bunny

2021-05-30 12:46 UTC, ThalusA requested changes

2021-05-30 12:46 UTC, ThalusA commented on src/types/schemas/Event.ts
> +   * Date time at the event occurred
```suggestion
   * Date time at which the event occurred
```

2021-05-30 12:53 UTC, Drosaca commented on src/types/schemas/Event.ts
> +   * Date time at the event occurred
on which

2021-05-30 13:15 UTC, ThalusA approved these changes

2021-06-01 09:16 UTC, Maastrich approved these changes
LGTM

2021-06-07 18:17 UTC, jess-sys approved these changes

2021-06-07 18:18 UTC, merged