Fix Date on connexion
d4data-official/d4data-archive-lib pull request #89
Opened 2021-06-26 21:33 UTC by Drosaca

2021-06-26 21:40 UTC, jess-sys commented
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

2021-06-26 21:44 UTC, jess-sys requested changes

2021-06-26 21:44 UTC, jess-sys commented on src/classes/Standardizer/plugins/Discord/getters/getConnections.ts
> +        timestamp: new Date(row.timestamp.slice(1, -1)),
Use standard Date.parse() method : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

```suggestion
        timestamp: new Date(Date.parse(row.timestamp)),
```

2021-06-26 21:47 UTC, jess-sys approved these changes
OK. The data originating from Discord is so poorly formatted.

2021-06-26 21:48 UTC, jess-sys commented
Linked to https://youtrack.neutheria.org/issue/D4-17 (but does not resolves)

2021-09-16 00:43 UTC, super-bunny approved these changes
OK

2021-09-16 00:44 UTC, merged